language: R
warnings_are_errors: true
sudo: true
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
       - libproj-dev

matrix:
    include:
        - os: linux
          r: release
          dist: disco
          env:
           - BUILD_NAME=disco_release
           - R_CODECOV=true
        - os: linux
          r: devel
          dist: disco
        - os: linux
          r: oldrel
          dist: disco
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
          env:
           - BUILD_NAME=osx_release
           - R_CODECOV=true
          #- os: osx
          #r: devel
          #before_install: ''
          #disable_homebrew: true

after_success:
  - Rscript -e 'covr::codecov()'
