language: r
warnings_are_errors: true
sudo: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libproj-dev

matrix:
    include:
        - os: linux
          r: release
          dist: bionic  # 16.04
          env:
           - BUILD_NAME=bionic_release
           - R_CODECOV=true
        - os: linux
          r: devel
          dist: bionic
        - os: linux
          r: oldrel
          dist: bionic
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
          env:
           - BUILD_NAME=osx_release
           - R_CODECOV=true
          #- os: osx
          #r: devel
          #before_install: ''
          #disable_homebrew: true

after_success:
  - Rscript -e 'covr::codecov()'
