on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]

name: R-CMD-check-proj

jobs:
  R-CMD-check-proj:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) (${{ matrix.config.PROJ_VERSION }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release', PROJ_VERSION: 'cran'}
          - {os: windows-latest, r: 'release', PROJ_VERSION: 'cran'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release', PROJ_VERSION: '9.3.0'}
          - {os: ubuntu-latest,   r: 'release', PROJ_VERSION: '9.3.0'}
          - {os: ubuntu-latest,   r: 'oldrel-1', PROJ_VERSION: '9.3.0'}
          - {os: ubuntu-latest,   r: 'release', PROJ_VERSION: '8.2.1'}
          - {os: ubuntu-latest,   r: 'release', PROJ_VERSION: '7.2.1'}
          - {os: ubuntu-latest,   r: 'release', PROJ_VERSION: '6.3.1'}
          - {os: ubuntu-latest,   r: 'release', PROJ_VERSION: '5.2.0'}
          - {os: ubuntu-latest,   r: 'release', PROJ_VERSION: '4.9.3'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      PROJ_NUMBER: ${{ matrix.config.PROJ_VERSION }}
    steps:
      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
           brew install openssl
           brew install proj

      - name: Install ubuntu system dependencies
        if: runner.os == 'Linux'
        run: |
           wget https://download.osgeo.org/proj/proj-$PROJ_NUMBER.tar.gz
           tar zxvf proj-$PROJ_NUMBER.tar.gz
           cd proj-$PROJ_NUMBER
           ./configure --prefix /usr
           make install -j4
           sudo make install
           sudo ldconfig

      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
